import 'api.dart';

const List<String> stateListText=[
  'Andaman and Nicobar Islands',
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chandigarh',
  'Chhattisgarh',
  'Dadra and Nagar Haveli',
  'Daman and Diu',
  'Delhi',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jammu and Kashmir',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Ladakh',
  'Lakshadweep',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Puducherry',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
];

const List<int> stateListKey=[
  1,2,3,4,5,6,7,8,9,10,
  11,12,13,14,15,16,17,
  18,19,20,21,22,23,24,
  25,26,27,28,29,30,31,
  32,33,34,35,36,];

var mapState ={1:'Andaman and Nicobar Islands',2:'Andhra Pradesh',3:'Arunachal Pradesh',
  4:'Assam',5:'Bihar',6:'Chandigarh',7:'Chhattisgarh',8:'Dadra and Nagar Haveli',
  9:'Delhi',10:'Goa',11:'Gujarat',12:'Haryana',13:'Himachal Pradesh',14:'Jammu and Kashmir',
  15:'Jharkhand',16:'Karnataka',17:'Kerala',18:'Ladakh',19:'Lakshadweep',20:'Madhya Pradesh',
  21:'Maharashtra',22:'Manipur',23:'Meghalaya',24:'Mizoram',25:'Nagaland',26:'Odisha',
  27:'Puducherry',28:'Punjab',29:'Rajasthan',30:'Sikkim',31:'Tamil Nadu',32:'Telangana',
  33:'Tripura',34:'Uttar Pradesh',35:'Uttarakhand',36:'West Bengal',37:'Daman and Diu',
};